application: trackmybus
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /css
  static_dir: static/css
  
- url: /js/jquery
  static_dir: static/jquery/js
  
- url: /images
  static_dir: static/images
  
- url: /js
  static_dir: static/js
  
- url: /.*
  script: main.py